### ISSUE TITLE
Dynamic allocation of ports for RTP from the data server to SDSC servers

### ISSUE THREAD

**Issue by ameyasingh** [UCSD-E4E/ASM-data-server#12]

**Comment by ntlhui** [comment]
SDSC servers need to explicitly add ports to open.  The Data Server currently allocates an arbitrary free port to use for the RTP server.

We need to add a feature that allocates a port from a predefined block of ports, and maintains the active status of those ports.  This block should be specified in the config file.  The server should then treat these as "allocated" to the Data Server, and not allocate them to any other services.

**Comment by ntlhui** [comment]
For example: assign port block: 9500-9600

First RTSP server will take port 9500
Second RTSP server will take port 9501
...
when RTSP servers close, the port is released back into the pool and is available for the next RTSP server

```
class PortProvider
{
    PortProvider(start, stop)
    int reservePort()
    void releasePort()
}
```

Couple options for managing ports:
1. bit map - array of bitflags indicating whether or not the port is open
2. Dict[int, bool] - each port is a key, value is the status
3. Linked List/stack - top is available, take off top to reserve, push back on to release

**Comment by ntlhui** [comment]
Implement in `DataServer/portAllocator.py` (https://github.com/UCSD-E4E/ASM-data-server/blob/main/DataServer/portAllocator.py)
