### ISSUE TITLE
Bug: Data transfer halting

### ISSUE THREAD

**Issue by clairma01** [UCSD-E4E/ASM-data-server#16]
While the on box sensor node and the data server are running, data is successfully transferred over for around 15-20 minutes, then halts. The on box sensor node needs to be stopped and restarted for data transfer to continue.

**Comment by ntlhui** [comment]
Can you replicate this on a clean working branch?  Please add information about which branch and commit were used.

**Comment by ntlhui** [comment]
Not getting this issue on clean working branches.  Problem may have been the inclusion of '-timeout 2000' on a dirty server branch.  @clairma01 please replicate

**Comment by clairma01** [comment]
I am still getting the issue on branch main, commit 77a7815

**Comment by ntlhui** [comment]
This still encountered on Data Server commit 31466a6, Sensor Node commit d9237a7.

This is running on the SDSC server.

Log indicates initialization at 2021.11.21 23:02:19.  FFMPEG instances created on ports 10001 and 10002 at 2021.11.22 08:06:47 and 2021.11.21.10:23

**Comment by ntlhui** [comment]
Note: Data server FFMPEG seemed to be frozen on `sudo service asm_server restart`
